import { Deposit } from "./application/usecase/Deposit.ts";
import ExecuteOrder from "./application/usecase/ExecuteOrder.ts";
import { GetAccount } from "./application/usecase/GetAccount.ts";
import GetOrder from "./application/usecase/GetOrder.ts";
import PlaceOrder from "./application/usecase/PlaceOrder.ts";
import { Signup } from "./application/usecase/Signup.ts";
import AccountController from "./infra/controller/AccountController.ts";
import OrderController from "./infra/controller/OrderController.ts";
import { PgPromiseAdapter } from "./infra/database/DatabaseConnection.ts";
import { PaymentGatewayHttp } from "./infra/gateway/PaymentGateway.ts";
import Mediator from "./infra/handler/Mediator.ts";
import OrderHandler from "./infra/handler/OrderHandler.ts";
import { FetchAdapter } from "./infra/http/HttpClient.ts";
import { ExpressAdapter } from "./infra/http/HttpServer.ts";
import ORM from "./infra/orm/ORM.ts";
import { AccountRepositoryDatabase, AccountRepositoryORM } from "./infra/repository/AccountRepository.ts";
import { OrderRepositoryDatabase } from "./infra/repository/OrderRepository.ts";
import { TradeRepositoryDatabase } from "./infra/repository/TradeRepository.ts";
import { WalletRepositoryDatabase } from "./infra/repository/WalletRepository.ts";

const databaseConnection = new PgPromiseAdapter();
const httpServer = new ExpressAdapter();
// const httpServer = new HapiAdapter();
// const httpClient = new AxiosAdapter();
const httpClient = new FetchAdapter();
const mediator = new Mediator();
const orm = new ORM(databaseConnection);
// const accountRepository = new AccountRepositoryDatabase(databaseConnection);
const accountRepository = new AccountRepositoryORM(orm);
const orderRepository = new OrderRepositoryDatabase(databaseConnection);
const tradeRepository = new TradeRepositoryDatabase(databaseConnection);
const walletRepository = new WalletRepositoryDatabase(databaseConnection);
const paymentGateway = new PaymentGatewayHttp(httpClient);
const signup = new Signup(accountRepository);
const getAccount = new GetAccount(accountRepository, walletRepository);
const deposit = new Deposit(accountRepository, walletRepository, paymentGateway);
const executeOrder = new ExecuteOrder(orderRepository, tradeRepository);
const placeOrder = new PlaceOrder(accountRepository, orderRepository, mediator);
const getOrder = new GetOrder(orderRepository);
new OrderHandler(mediator, executeOrder);
new AccountController(httpServer, signup, getAccount);
new OrderController(httpServer, placeOrder, getOrder);
httpServer.listen(3000);
