import AccountController from "./AccountController.ts";
import { AccountRepositoryDatabase } from "./AccountRepository.ts";
import API from "./api.ts";
import { PgPromiseAdapter } from "./DatabaseConnection.ts";
import { Deposit } from "./Deposit.ts";
import ExecuteOrder from "./ExecuteOrder.ts";
import { GetAccount } from "./GetAccount.ts";
import GetOrder from "./GetOrder.ts";
import { AxiosAdapter, FetchAdapter } from "./HttpClient.ts";
import { ExpressAdapter, HapiAdapter } from "./HttpServer.ts";
import Mediator from "./Mediator.ts";
import OrderController from "./OrderController.ts";
import OrderHandler from "./OrderHandler.ts";
import { OrderRepositoryDatabase } from "./OrderRepository.ts";
import { PaymentGatewayHttp } from "./PaymentGateway.ts";
import PlaceOrder from "./PlaceOrder.ts";
import { Signup } from "./Signup.ts";

const databaseConnection = new PgPromiseAdapter();
const httpServer = new ExpressAdapter();
// const httpServer = new HapiAdapter();
// const httpClient = new AxiosAdapter();
const httpClient = new FetchAdapter();
const mediator = new Mediator();
const accountRepository = new AccountRepositoryDatabase(databaseConnection);
const orderRepository = new OrderRepositoryDatabase(databaseConnection);
const paymentGateway = new PaymentGatewayHttp(httpClient);
const signup = new Signup(accountRepository);
const getAccount = new GetAccount(accountRepository);
const deposit = new Deposit(accountRepository, paymentGateway);
const executeOrder = new ExecuteOrder(orderRepository);
const placeOrder = new PlaceOrder(accountRepository, orderRepository, mediator);
const getOrder = new GetOrder(orderRepository);
new OrderHandler(mediator, executeOrder);
new AccountController(httpServer, signup, getAccount);
new OrderController(httpServer, placeOrder, getOrder);
httpServer.listen(3000);
